# version: '3.8'

# services:
#   jenkins:
#     image: jenkins/jenkins:lts
#     ports:
#       - "8080:8080"
#       - "50000:50000"
#     volumes:
#       - jenkins_home:/var/jenkins_home

# volumes:
#   jenkins_home:

# version: '3.8'

# services:
#   jenkins:
#     image: jenkins/jenkins:lts
#     container_name: jenkins
#     ports:
#       - "192.168.1.51:8080:8080"
#       - "192.168.1.51:50000:50000"
#     volumes:
#       - jenkins_home:/var/jenkins_home

# volumes:
#   jenkins_home:

# version: '3.8'

# services:
#   jenkins:
#     image: jenkins/jenkins:lts
#     container_name: jenkins
#     ports:
#       - "192.168.1.51:8080:8080"
#       - "192.168.1.51:50000:50000"
#     volumes:
#       - jenkins_home:/var/jenkins_home
#       - /var/run/docker.sock:/var/run/docker.sock  # <-- This is required for Docker CLI access inside Jenkins

# volumes:
#   jenkins_home:


version: '3.8'

services:
  jenkins:
    build: .                      # Add this if you want to build from your custom Dockerfile in the same folder
    image: custom-jenkins-jdk    # optional, for naming your custom image
    container_name: jenkins
    ports:
      - "192.168.1.51:8080:8080"
      - "192.168.1.51:50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Docker CLI inside Jenkins

volumes:
  jenkins_home:

